### ISSUE TITLE
Coalesce 0-RTT packets with Initial

### ISSUE THREAD

**Issue by ghedo** [QUIC-Tracker/quic-tracker#16]
In the 0-RTT test I see packets consistently arriving in the wrong order (0-RTT first, then Initial). It's not quite clear to me if the problem is my server or not, but it would be nice if quic-tracker could coalesce those packets together, so we wouldn't have to workaround this while debugging the 0-RTT test failures.

**Comment by mpiraux** [comment]
The way I wired up 0-RTT makes it a bit complicated but it does make sense of course. I am guessing one of those strange middleboxes could be involved in that issue.

**Comment by mpiraux** [comment]
I did implement that sometimes ago, but the test still fails: https://quic-tracker.info.ucl.ac.be/traces/20200422/522 confirms that the initials and 0-RTT packets are coalesced but the latter gets no ACK.

**Comment by mpiraux** [comment]
I close this here and bring that to the Slack.
