### ISSUE TITLE
New test: multi-packet ClientHello

### ISSUE THREAD

**Issue by ghedo** [QUIC-Tracker/quic-tracker#17]
The next draft will allow splitting ClientHello messages across Initial packets, so it'd be nice if quic-tracker had a test for it. For example, the TLS padding extension could be added to the ClientHello message by quic-tracker such that the message would be bigger than MTU.

It would also be nice if quic-tracker could swap those packets (send second packet first, then the first one after a delay), to see if the server can process that.

**Comment by mpiraux** [comment]
I think I will split the crypto stream as is and put into two frames and put them in separate packets. Adding that padding extension is more complicated to wire up and impose slightly more burden on the tls stack than the QUIC one.

**Comment by dtikhonov** [comment]
The padding is included as a [QUIC transport parameter](https://github.com/quicwg/base-drafts/wiki/Quantum-Readiness-test), not as TLS extension.

**Comment by mpiraux** [comment]
I wrote a quick test to cut my existing CRYPTO frame in half and send it in two pieces, padded with PADDING frames. That's good enough to test whether implementations buffer out-of-order Initials IMO. 

I could add another test for the following MUST though:

> 7.4.  Cryptographic Message Buffering
> ...
> Implementations MUST support buffering at least 4096 bytes of data
> received in CRYPTO frames out of order.
In that case I will probably add that QUIC TP.

**Comment by ghedo** [comment]
Yeah, splitting CRYPTO into two sounds good as well :+1:

**Comment by mpiraux** [comment]
I actually pushed that test in November: https://github.com/QUIC-Tracker/quic-tracker/blob/master/scenarii/multi_packet_client_hello.go.
