### ISSUE TITLE
pcap_completed_error with http3_get scenario

### ISSUE THREAD

**Issue by piano-man** [QUIC-Tracker/quic-tracker#18]
When I try to execute the http3_get scenario against the cloudflare host (quic.tech:8443) it ends up giving a pcap_completed_error. Any specific reason for this ?

**Comment by mpiraux** [comment]
What's the error exactly ? Remember that capturing network traffic may require administrative priviledge on your machine. The error is likely due to the lack of those priviledges.

**Comment by piano-man** [comment]
Yup. It was happening because I was executing the scripts on WSL and WSL doesn't provide access to raw sockets I believe.
Thanks.
