### ISSUE TITLE
Possible issue in the initial ClientHello packet 

### ISSUE THREAD

**Issue by piano-man** [QUIC-Tracker/quic-tracker#22]
When I try to use quic-tracker with a mozilla/neqo server, the handshake never completes and the server runs into an error. I raised the issue with the developers of neqo and according to them, the client is not behaving in the appropriate manner. I'm attaching a link to the issue for reference :- 

https://github.com/mozilla/neqo/issues/555#issuecomment-616896608

**Comment by martinthomson** [comment]
I have just confirmed, via code inspection, that the version of picotls you use always invokes TLS 1.3 compatibility mode.

**Comment by mpiraux** [comment]
Thank you guys for reporting this! I guess I have to wait for https://github.com/h2o/picotls/pull/305 to get merged and then update picotls.

**Comment by mpiraux** [comment]
The fix has been merged in https://github.com/mpiraux/pigotls/commit/b401335476226e98df8205b46e27c30d5ccbb021. It should be up on the live instance as well.
