### ISSUE TITLE
Viewing/processing test_suite results

### ISSUE THREAD

**Issue by silverbucket** [QUIC-Tracker/quic-tracker#26]
I'm able to run the full test suite against a QUIC server, and the JSON output contains all of the details of the tests, however I'm not sure what to do with these data after the suite is complete. I was under the impression that the docker image also provided the web interface to view results, is this the case or is there another process that perhaps isn't documented? 

Also as a side node, the publicly available instance `https://quic-tracker.info.ucl.ac.be/traces` is currently throwing exceptions when you try to view some of the trace results. For example: https://quic-tracker.info.ucl.ac.be/traces/20200729/300

**Comment by mpiraux** [comment]
> I'm able to run the full test suite against a QUIC server, and the JSON output contains all of the details of the tests, however I'm not sure what to do with these data after the suite is complete. I was under the impression that the docker image also provided the web interface to view results, is this the case or is there another process that perhaps isn't documented?

The web application is not packaged in the docker image unfortunately. I will add it in the very near future, it's sensible to put it along the test suite docker image. In the meanwhile there exists some documentation on how to use it in [the scenario tutorial](https://quic-tracker.info.ucl.ac.be/blog/tutorial/2018/11/21/tutorial-creating-a-scenario.html).

> Also as a side node, the publicly available instance https://quic-tracker.info.ucl.ac.be/traces is currently throwing exceptions when you try to view some of the trace results. For example: https://quic-tracker.info.ucl.ac.be/traces/20200729/300

Thanks for reporting it. It's fixed now :)

**Comment by mpiraux** [comment]
I added the web app to the Docker image and updated the README. I managed to screw up my Docker hub organisation, so update the Docker image repository accordingly.

**Comment by mpiraux** [comment]
One last point, give `-output $(date '+\%Y\%m\%d.json')` to the test suite to generate a file name that can be found by the web app inside the `traces` directory. Don't hesitate to reopen the issue if you are still encountering issues.

**Comment by silverbucket** [comment]
@mpiraux awesome, thanks. I'll give it a show now.

**Comment by silverbucket** [comment]
@mpiraux I haven't been able to get the flask app within docker to read the file in the `traces` directory of my working dir. Output the filenames as `20200803.json` or `\2020\08\03.json` and placing them in the traces directory doesn't work. Does the file need to be inside the docker container or can't it be in the `traces` directory off of the working dir? I think I'm missing something obvious but this is a bit of a black box for me at the moment :)

**Comment by mpiraux** [comment]
Just put trace files in the working dir where you ran `docker run -v "$PWD:/traces" -p 5000:5000 mpiraux/quictracker flask run -h 0.0.0.0`. Remove the backslashes as well. If you are running this from a directory that contain your `traces` dir, you could also run `docker run -v "$PWD/traces:/traces" -p 5000:5000 mpiraux/quictracker flask run -h 0.0.0.0` instead.
