### ISSUE TITLE
Changes 4 days ago created lots of crashes of scenarios

### ISSUE THREAD

**Issue by silverbucket** [QUIC-Tracker/quic-tracker#29]
Hello, we're currently running an instance of quic-tracker via docker on our internal network. Things have been working fine for the past year, but 4 days ago we started getting a lot of a grey squares saying the test crashed.

There's no information data in the traces/dissector page, neither on the console, even though we are running things with the -debug flag set. Is there any way to get more info about the crash? 

Since it's doesn't seem to be tied to any one server that's being tested. And the instance you run doesn't seem to be effected. It seems like it has something to do with the combination of the network we're running from (possibly docker?) and the new expectations you've added to the code.

**Comment by silverbucket** [comment]
* Before
![Screen Shot 2022-03-15 at 15 48 38](https://user-images.githubusercontent.com/317571/158404529-9061100d-affa-408f-be5b-652b815fb980.jpg)
* After
![Screen Shot 2022-03-15 at 15 49 11](https://user-images.githubusercontent.com/317571/158404559-9108feb7-f056-4b2d-9d5c-9b6439be3708.jpg)

**Comment by mpiraux** [comment]
Hello, I was able to reproduce the issue by using the scenario_runner with the http3_get scenario on test.privateoctopus.com:4433. It is effectively only impacting the Docker image somehow. 36255f1 fixed the issue on my side, could you confirm it does also on yours?

Unfortunately it was a Go programming error so it does not appear in the logs.

**Comment by silverbucket** [comment]
Thanks for the quick feedback @mpiraux - Our automated jobs will run tonight and automatically grab the latest, so I'll let you know how it looks tomorrow. Cheers

**Comment by silverbucket** [comment]
@mpiraux I can confirm everything works now as it did before, thanks for your help!
