### ISSUE TITLE
Installation instructions in README.rst are incorrect

### ISSUE THREAD

**Issue by dtikhonov** [QUIC-Tracker/quic-tracker#4]
Issuing `go get` command does not result in the package being installed:

```
[dmitri@ubuntu-dmitri proj]$ go get github.com/QUIC-Tracker/quic-tracker
# github.com/mpiraux/ls-qpack-go
gcc: error: ../go/src/github.com/mpiraux/ls-qpack-go/ls-qpack/libls-qpack.a: No such file or directory
gcc: error: ../go/src/github.com/mpiraux/ls-qpack-go/ls-qpack/bin/CMakeFiles/interop-encode.dir/__/deps/xxhash/xxhash.c.o: No such file or directory
# github.com/mpiraux/pigotls
gcc: error: ../go/src/github.com/mpiraux/pigotls/picotls/libpicotls-core.a: No such file or directory
gcc: error: ../go/src/github.com/mpiraux/pigotls/picotls/libpicotls-openssl.a: No such file or directory
[dmitri@ubuntu-dmitri proj]$
```

I use go 1.9.7

**Comment by mpiraux** [comment]
This will always fail actually. I was not able to tie those dependencies build systems with the go packaging tools. Thats why you need to `make` the two, as indicated in the (updated) README.rst, see 43ba147.

**Comment by dtikhonov** [comment]
OK -- I just wanted to bring this to your attention.  You can close the bug if there is nothing to be done.

I had to do quite a bit more than just typing a few `make` commands, though:  I had to compile picotls and ls-qpack; pass correct flags to the linker (via some cgo environment variables) so that libraries could be linked; and finally copy some `.o` file to $GOPATH by hand.  Pretty much, I hacked away at it (for some time) until it worked.  A person that is more familiar with Go development may have an easier time.

**Comment by mpiraux** [comment]
> I had to do quite a bit more than just typing a few make commands, though: I had to compile picotls and ls-qpack; pass correct flags to the linker (via some cgo environment variables) so that libraries could be linked; and finally copy some .o file to $GOPATH by hand. Pretty much, I hacked away at it (for some time) until it worked. A person that is more familiar with Go development may have an easier time.

This should be taken care of by the Makefiles I wrote for the two bindings actualy. I remember having portability issues with the `.ONESHELL`, see https://github.com/mpiraux/pigotls/issues/1. Are you using GNU make or BSD make ? It is known to work with GNU make, but not BSD make. I should make that clear in the README.
